EN-1928 started consolidating reusable files

diff --git a/Docker/base-images/entando-eap71-base/s2i/bin/assemble b/Docker/base-images/entando-eap71-base/s2i/bin/assemble
--- a/Docker/base-images/entando-eap71-base/s2i/bin/assemble
+++ b/Docker/base-images/entando-eap71-base/s2i/bin/assemble
@@ -43,7 +43,10 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
   # Add JVM default options
   export MAVEN_OPTS="${MAVEN_OPTS:-$(/opt/run-java/java-default-options)}"
   if [ "$PREPARE_DB" = "true" ]; then
-    $(dirname ${BASH_SOURCE[0]})/init-db.sh
+    if ! $($(dirname ${BASH_SOURCE[0]})/init-db.sh; then
+        echo "DB Preparation failed!"
+        exit 1
+    fi
   fi
 
   MAVEN_ARGS="${MAVEN_ARGS} --e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga clean package"
diff --git a/Docker/base-images/entando-wildfly12-base/s2i/bin/assemble b/Docker/base-images/entando-wildfly12-base/s2i/bin/assemble
--- a/Docker/base-images/entando-wildfly12-base/s2i/bin/assemble
+++ b/Docker/base-images/entando-wildfly12-base/s2i/bin/assemble
@@ -315,6 +315,13 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
   echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
 
   mvn --version
+  if [ "$PREPARE_DB" = "true" ]; then
+    if ! $($(dirname ${BASH_SOURCE[0]})/init-db.sh; then
+        echo "DB Preparation failed!"
+        exit 1
+    fi
+  fi
+
   mvn $MAVEN_ARGS
 
   ERR=$?
